"""modelo inicial

Revision ID: dd4b27164da0
Revises: 
Create Date: 2026-08-26 22:33:26.616277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd4b27164da0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('license', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('time_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dataset_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=False),
    sa.Column('dataset_version', sa.String(length=64), nullable=False),
    sa.Column('feature_schema', sa.JSON(), nullable=False),
    sa.Column('hyperparameters', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('git_commit', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('confusion_matrix', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('quality_report', sa.JSON(), nullable=False),
    sa.Column('pipeline_version', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('health_index', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('feature_contributions', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_file', sa.String(length=64), nullable=False),
    sa.Column('split', sa.String(length=16), nullable=False),
    sa.Column('generator_power', sa.Float(), nullable=True),
    sa.Column('unit_speed_pct', sa.Float(), nullable=True),
    sa.Column('temp_thrust_pad1', sa.Float(), nullable=True),
    sa.Column('temp_upper_guide_pad1', sa.Float(), nullable=True),
    sa.Column('temp_lower_guide_pad1', sa.Float(), nullable=True),
    sa.Column('temp_turbine_guide_pad1', sa.Float(), nullable=True),
    sa.Column('vib_ugb_x', sa.Float(), nullable=True),
    sa.Column('vib_ugb_y', sa.Float(), nullable=True),
    sa.Column('vib_ugb_z', sa.Float(), nullable=True),
    sa.Column('vib_lgb_x', sa.Float(), nullable=True),
    sa.Column('vib_lgb_y', sa.Float(), nullable=True),
    sa.Column('vib_tgb_x', sa.Float(), nullable=True),
    sa.Column('quality_flags', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prediction_run_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_run_id'], ['prediction_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_table('signal_samples')
    op.drop_table('prediction_runs')
    op.drop_table('ingestion_runs')
    op.drop_table('evaluation_runs')
    op.drop_table('model_versions')
    op.drop_table('datasets')
    # ### end Alembic commands ###
